name: iproov_flutter
description: The iProov Face SDK for Flutter, providing flexible authentication for identity assurance
version: 6.0.0
homepage: https://github.com/iProov/flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.iproov.sdk
        pluginClass: IProovSDKPlugin

      ios:
        pluginClass: IProovSDKPlugin
